# UAPI Header export list
include include/uapi/asm-generic/Kbuild.asm

header-y += byteorder.h
header-y += param.h
header-y += ptrace.h
header-y += sigcontext.h
header-y += spr_defs.h
header-y += unistd.h
